# Generated by Django 4.2.3 on 2023-07-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPasteBin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='content',
            field=models.TextField(),
        ),
    ]
